# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
#  build:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          ref: ${{ github.head_ref }}
#      - name: Set up Python 3.12
#        uses: actions/setup-python@v3
#        with:
#          python-version: "3.12"
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#      - name: Recreate config.ini
#        run: |
#          rm config.ini
#          cp config.example.ini config.ini
#      - uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          commit_message: "Replace config.ini"
#          file_pattern: "config.ini"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install dependencies
        run: |
          pip install flake8 pytest
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
